# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 网站标题
brief-intro: 网站描述
home_title: 主页标题
home_description: 主页描述
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.kongkongye.com" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_username: kongkongye
email: kongkongye@163.com
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

description_footer: 底部描述!

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 15095585476eb792ca88ce3679191070
google_analytics_id: UA-93246511-1 # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6

keep_files: ["imgs"]
